# must be unique in a given SonarQube instance
sonar.organization=mohkharma
sonar.projectKey=mohkharma_middleware
sonar.gradle.skipCompile =true

# Path is relative to the sonar-project.properties file. Defaults to .
sonar.sources=./src
sonar.java.binaries = ./target/classes

#sonar.sourceEncoding=UTF-8
#sonar.host.url=http://localhost:9000/
sonar.host.url=https://sonarcloud.io
sonar.login=26c9cfc1af5d2f7c9472903e2a02be42cddbe171
#sonar.login=sqp_63b20fb5ec12ee892ff5cddef124162a9e57bd93
sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-
sonar.python.version=3
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml

