server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
    

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org.springframework.web: DEBUG
    com.middleware.backend: DEBUG

camel:
  rest:
    component: servlet     # or netty-http, undertow, http, etc. depending on your setup
    host: localhost
    port: 8081
    context-path: /camel    # optional, base context path for your REST endpoints
  servlet:
    mapping:
      context-path: /camel/*

      