server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/middleware2
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        # Quartz properties
      quartz:
        properties:
          spring.quartz.job-store-type: jdbc
          spring.quartz.jdbc.initialize-schema: always
#          spring.quartz.properties.org.quartz.jobStore.isClustered: false
#          spring.quartz.properties.org.quartz.scheduler.instanceId: AUTO

# JWT SECRET
jwt:
  secret: 1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p

management:
  health:
    rabbit:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    org.springframework.web: DEBUG
    com.middleware.backend: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

camel:
  main:
    scripting: true
  rest:
    component: servlet     # or netty-http, undertow, http, etc. depending on your setup
    host: localhost
    port: 8081
    context-path: /camel    # optional, base context path for your REST endpoints
  servlet:
    mapping:
      context-path: /camel/*

# DHIS2 Configuration
dhis2:
  base-url: https://play.im.dhis2.org/stable-2-41-5
  username: admin
  password: district
  timeout: 30000
  connect-timeout: 10000

