server:
  port: 8081

spring:
  datasource:
    #    url: jdbc:postgresql://localhost:5432/middleware2
    #    url: jdbc:postgresql://localhost:5432/design_table
    url: jdbc:postgresql://localhost:5432/middlewaretest
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding=true:
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        # Quartz properties
      quartz:
        properties:
          spring.quartz.job-store-type: jdbc
          spring.quartz.jdbc.initialize-schema: always
#          spring.quartz.properties.org.quartz.jobStore.isClustered: false
#          spring.quartz.properties.org.quartz.scheduler.instanceId: AUTO
#STATIC EMAIL CONFIG
  mail:
    host: smtp.gmail.com
    port: 587
    username: mohammadkadoumi77@gmail.com
    password: tcpf gpzv mfki eyfn
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      from: no-reply@middleware.org

app:
  security:
    auth-mode: application


# JWT SECRET
jwt:
  secret: 1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p





#keycloak:
#  realm: middleware
#  auth-server-url: http://localhost:8082
#  client-id: middleware-client
#  client-secret: yzFOmARMUvUWB7k8hURtr0JksgjobGMw
#  redirect-uri: http://localhost:8081/api/auth/keycloak/exchange

security:
  keycloak:
    server-url: http://localhost:8082
    realm: middleware
    client-id: middleware-client
    client-secret: iXaRoUGkc0kPb2FcspkCQFiGACbMkjfp
    redirect-uri: http://localhost:8081/api/auth/keycloak/exchange
keycloak:
  admin:
    username: admin
    password: admin
management:
  health:
    rabbit:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    org.springframework.web: DEBUG
    com.middleware.backend: DEBUG
    org.apache.camel: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

camel:
  main:
    scripting: true
    stream-caching-enabled: true
    stream-caching-spool-enabled: true
    stream-caching-any-spool-rules: true
    stream-caching-spool-used-heap-memory-threshold: 70
  rest:
    component: servlet     # or netty-http, undertow, http, etc. depending on your setup
    host: localhost
    port: 8081
    context-path: /camel    # optional, base context path for your REST endpoints
  servlet:
    mapping:
      context-path: /camel/*
  component:
    http:
      follow-redirects: true
    https:
      follow-redirects: true
  ssl:
    config:
      trust-all: true
      verify-hostname: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tryItOutEnabled: true
    operationsSorter: alpha
    tagsSorter: alpha

cache:
  type: simple
  cache-names:
    - dhis2-responses
    - metadata-cache
    - api-definitions



#http://localhost:8081/swagger-ui/index.html
#https://generate-uuid.com/?utm_source=chatgpt.com#