apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleware-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: your-dockerhub-username/middleware-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/middleware_db
            - name: SPRING_DATASOURCE_USERNAME
              value: youruser
            - name: SPRING_DATASOURCE_PASSWORD
              value: yourpass
