package com.middleware.backend.logging.model;

import java.time.LocalDateTime;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Entity representing a single middleware API call attempt (or retry).
 * Uniqueness is enforced on the pair (source_transaction_uuid, attempt_no) and transaction_id.
 */
@Entity
@Table(
        name = "middleware_api_call_log",
        uniqueConstraints = {
                @UniqueConstraint(name = "uk_call_uuid_attempt", columnNames = {"source_transaction_uuid", "attempt_no"}),
                @UniqueConstraint(name = "uk_transaction_id", columnNames = {"transaction_id"})
        }
)
@Getter @Setter @ToString @NoArgsConstructor @AllArgsConstructor @Builder
public class MiddlewareApiCallLog {

        /** Database primary key. */
        @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

        /** Unique internal transaction identifier generated by the middleware. */
        @Column(name = "transaction_id", nullable = false, unique = true, length = 36)
    private String transactionId;

        /** Camel route identifier handling the request. */
        @Column(name = "route_Id", nullable = false)
    private String routeId;

        /** Endpoint URI or logical API identifier. */
        @Column(name = "api_endpoint")
    private String apiEndpoint;

        /** HTTP method. */
        @Column(name = "request_method", length = 10)
    private String requestMethod;

        /** Full request URL. */
        @Column(name = "request_url", length = 2048)
    private String requestUrl;

        /** Request path portion (without scheme/host). */
        @Column(name = "request_path", length = 1024)
    private String requestPath;

        /** Query string as received. */
        @Column(name = "request_query", length = 2048)
    private String requestQuery;

        /** Request headers serialized to string. */
        @Column(name = "request_headers", columnDefinition = "TEXT")
    private String requestHeaders;

        /** Request body serialized to string. */
        @Column(name = "request_body", columnDefinition = "TEXT")
    private String requestBody;

        /** Processing status (IN_PROGRESS, COMPLETED, FAILED). */
        @Column(name = "status", length = 20)
    private String status;

        /** HTTP response status code. */
        @Column(name = "response_code")
    private Integer responseCode;

        /** Response headers serialized to string. */
        @Column(name = "response_headers", columnDefinition = "TEXT")
    private String responseHeaders;

        /** Response body serialized to string. */
        @Column(name = "response_body", columnDefinition = "TEXT")
    private String responseBody;

        /** Timestamp when request was received. */
        @Column(name = "received_at")
    private LocalDateTime receivedAt;

        /** Timestamp when processing completed. */
        @Column(name = "completed_at")
    private LocalDateTime completedAt;

        /** Total processing duration in milliseconds. */
        @Column(name = "duration_ms")
    private Long durationMs;

        /** Detected client IP address. */
        @Column(name = "client_ip", length = 100)
    private String clientIp;

        /** Optional API key identifier when present. */
        @Column(name = "api_key_id")
    private Long apiKeyId;

        /** Email/identifier of the user from the JWT, if provided. */
        @Column(name = "user_id", length = 255)
    private String userId;

        /** Error message captured from exception or HTTP response. */
        @Column(name = "error_message", columnDefinition = "TEXT")
    private String errorMessage;

        /** Number of retries attempted for this source transaction. */
        @Column(name = "retry_count")
    private Integer retryCount;                

        /** Sequential attempt number for the given source transaction UUID. */
        @Column(name = "attempt_no", nullable = false)
    private Integer attemptNo;

        /** Client-provided correlation id used across attempts. */
        @Column(name = "source_transaction_uuid", length = 36, nullable = false)
    private String sourceTransactionUUID;
}
